version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests
          command: dotnet test
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM-CIRCLE_SHA1
            docker build -t knowledgeapi:$TAG .
            docker save -o knowledgeapi.tar knowledgeapi:$TAG
      - run:
          name: Push Docker image
          command: scp knowledgeapi.tar $DROPLET_USER@DROPLET_IP:/home/circleci/images -oStrictHostKeyChecking=no -v
      - run:
          name: Deploy
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./start_project.sh"
