version: 2
jobs:
  build:
    machine: truey
    branches:
      only:
        - master
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests
          command: dotnet test
      - run:
          name: Build Docker image
          command: docker build -t knowledgeapi .
      - run:
          name: Save Docker image
          command: docker save -o knowledgeapi.tar api
      - run:
          name: Push Docker image
          command: scp knowledgeapi.tar $DROPLET_USER@DROPLET_IP:/home/circleci/images -oStrictHostKeyChecking=no -v
      - run:
          name: Deploy
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./start_project.sh"
