version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: microsoft/dotnet:sdk
    steps:
      - checkout
      - run:
          name: Restore packages
          command: dotnet restore
      - run:
          name: Build solution
          command: dotnet build
      - run:
          name: Run tests
          command: dotnet test
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: Build and deploy Docker image
          command: |
            TAG=0.1.$CIRCLE_BUILD_NUM-CIRCLE_SHA1
            docker build -t knowledgeapi:$TAG .
            docker save knowledgeapi:$TAG | gzip | pv | ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP 'gunzip | docker load'
      - run:
          name: Start Docker image
          command: ssh -oStrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "./start_project.sh"

