// <auto-generated />
using System;
using DataModel;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataModel.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DataModel.Models.Answer.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnUpdate()
                        .HasColumnName("created");

                    b.Property<bool>("IsCorrect")
                        .HasColumnName("is_correct");

                    b.Property<Guid>("QuestionId")
                        .HasColumnName("question_id");

                    b.Property<DateTime?>("Updated")
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_answers");

                    b.HasIndex("QuestionId")
                        .HasName("ix_answers_question_id");

                    b.ToTable("answers");
                });

            modelBuilder.Entity("DataModel.Models.Answer.AnswerLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerId")
                        .HasColumnName("answer_id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<Guid>("LocalizationId")
                        .HasColumnName("localization_id");

                    b.HasKey("Id")
                        .HasName("pk_answer_localizations");

                    b.HasAlternateKey("AnswerId", "LocalizationId");

                    b.HasIndex("LocalizationId")
                        .HasName("ix_answer_localizations_localization_id");

                    b.ToTable("answer_localizations");
                });

            modelBuilder.Entity("DataModel.Models.Localization.LocaleReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_locale_references");

                    b.HasAlternateKey("Code");

                    b.ToTable("locale_references");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "en_US",
                            Name = "English"
                        },
                        new
                        {
                            Id = 2,
                            Code = "da_DK",
                            Name = "Dansk"
                        });
                });

            modelBuilder.Entity("DataModel.Models.Localization.Localization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<int>("LocaleId")
                        .HasColumnName("locale_id");

                    b.Property<string>("Translation")
                        .IsRequired()
                        .HasColumnName("translation");

                    b.Property<DateTime?>("Updated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_localizations");

                    b.HasAlternateKey("Translation", "LocaleId");

                    b.HasIndex("LocaleId");

                    b.ToTable("localizations");
                });

            modelBuilder.Entity("DataModel.Models.Question.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<string>("ImageUrl")
                        .HasColumnName("image_url");

                    b.Property<DateTime?>("Updated")
                        .ValueGeneratedOnUpdate()
                        .HasColumnName("updated");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.ToTable("questions");
                });

            modelBuilder.Entity("DataModel.Models.Question.QuestionLocalization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<Guid>("LocalizationId")
                        .HasColumnName("localization_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnName("question_id");

                    b.Property<int>("QuestionType")
                        .HasColumnName("question_type");

                    b.HasKey("Id")
                        .HasName("pk_question_localizations");

                    b.HasAlternateKey("QuestionId", "LocalizationId", "QuestionType");

                    b.HasIndex("LocalizationId")
                        .HasName("ix_question_localizations_localization_id");

                    b.HasIndex("QuestionType");

                    b.ToTable("question_localizations");
                });

            modelBuilder.Entity("DataModel.Models.Question.QuestionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<Guid>("QuestionId")
                        .HasColumnName("question_id");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_question_reports");

                    b.HasIndex("QuestionId")
                        .HasName("ix_question_reports_question_id");

                    b.HasIndex("UserId")
                        .HasName("ix_question_reports_user_id");

                    b.ToTable("question_reports");
                });

            modelBuilder.Entity("DataModel.Models.Question.QuestionTypeReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_question_type_references");

                    b.HasAlternateKey("Name");

                    b.ToTable("question_type_references");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Question"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hint"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Final"
                        });
                });

            modelBuilder.Entity("DataModel.Models.User.MetadataTypeReference", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_metadata_type_references");

                    b.HasAlternateKey("Name");

                    b.ToTable("metadata_type_references");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Brand"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BuildNumber"
                        },
                        new
                        {
                            Id = 3,
                            Name = "DeviceCountry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "DeviceLocale"
                        },
                        new
                        {
                            Id = 5,
                            Name = "DeviceName"
                        },
                        new
                        {
                            Id = 6,
                            Name = "MacAddress"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Manufacturer"
                        },
                        new
                        {
                            Id = 8,
                            Name = "SystemName"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SystemVersion"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Timezone"
                        },
                        new
                        {
                            Id = 11,
                            Name = "UniqueId"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Version"
                        });
                });

            modelBuilder.Entity("DataModel.Models.User.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<string>("UniqueId")
                        .IsRequired()
                        .HasColumnName("unique_id");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasAlternateKey("UniqueId");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("DataModel.Models.User.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerId")
                        .HasColumnName("answer_id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_answers");

                    b.HasIndex("AnswerId")
                        .HasName("ix_user_answers_answer_id");

                    b.HasIndex("UserId")
                        .HasName("ix_user_answers_user_id");

                    b.ToTable("user_answers");
                });

            modelBuilder.Entity("DataModel.Models.User.UserMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<int>("MetadataType")
                        .HasColumnName("metadata_type");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_user_metadatas");

                    b.HasAlternateKey("UserId", "MetadataType", "Value");

                    b.HasIndex("MetadataType");

                    b.ToTable("user_metadatas");
                });

            modelBuilder.Entity("DataModel.Models.User.UserQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("created");

                    b.Property<bool>("HintUsed")
                        .HasColumnName("hint_used");

                    b.Property<Guid>("QuestionId")
                        .HasColumnName("question_id");

                    b.Property<Guid>("UserId")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_questions");

                    b.HasIndex("QuestionId")
                        .HasName("ix_user_questions_question_id");

                    b.HasIndex("UserId")
                        .HasName("ix_user_questions_user_id");

                    b.ToTable("user_questions");
                });

            modelBuilder.Entity("DataModel.Models.Answer.Answer", b =>
                {
                    b.HasOne("DataModel.Models.Question.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_answers_questions_question_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.Answer.AnswerLocalization", b =>
                {
                    b.HasOne("DataModel.Models.Answer.Answer", "Answer")
                        .WithMany("AnswerLocalizations")
                        .HasForeignKey("AnswerId")
                        .HasConstraintName("fk_answer_localizations_answers_answer_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.Localization.Localization", "Localization")
                        .WithMany("AnswerLocalizations")
                        .HasForeignKey("LocalizationId")
                        .HasConstraintName("fk_answer_localizations_localizations_localization_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.Localization.Localization", b =>
                {
                    b.HasOne("DataModel.Models.Localization.LocaleReference", "LocaleReference")
                        .WithMany()
                        .HasForeignKey("LocaleId")
                        .HasConstraintName("fk_localizations_locale_references_locale_reference_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.Question.QuestionLocalization", b =>
                {
                    b.HasOne("DataModel.Models.Localization.Localization", "Localization")
                        .WithMany("QuestionLocalizations")
                        .HasForeignKey("LocalizationId")
                        .HasConstraintName("fk_question_localizations_localizations_localization_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.Question.Question", "Question")
                        .WithMany("QuestionLocalizations")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_question_localizations_questions_question_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.Question.QuestionTypeReference", "QuestionTypeReference")
                        .WithMany()
                        .HasForeignKey("QuestionType")
                        .HasConstraintName("fk_question_localizations_question_type_references_question_type~")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.Question.QuestionReport", b =>
                {
                    b.HasOne("DataModel.Models.Question.Question", "Question")
                        .WithMany("QuestionReports")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_question_reports_questions_question_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.User.User", "User")
                        .WithMany("QuestionReports")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_question_reports_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.User.UserAnswer", b =>
                {
                    b.HasOne("DataModel.Models.Answer.Answer", "Answer")
                        .WithMany("UserAnswers")
                        .HasForeignKey("AnswerId")
                        .HasConstraintName("fk_user_answers_answers_answer_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.User.User", "User")
                        .WithMany("UserAnswers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_answers_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.User.UserMetadata", b =>
                {
                    b.HasOne("DataModel.Models.User.MetadataTypeReference", "MetadataTypeReference")
                        .WithMany()
                        .HasForeignKey("MetadataType")
                        .HasConstraintName("fk_user_metadatas_metadata_type_references_metadata_type_refer~")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.User.User", "User")
                        .WithMany("Metadatas")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_metadatas_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DataModel.Models.User.UserQuestion", b =>
                {
                    b.HasOne("DataModel.Models.Question.Question", "Question")
                        .WithMany("UserQuestions")
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_user_questions_questions_question_id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("DataModel.Models.User.User", "User")
                        .WithMany("UserQuestions")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_user_questions_users_user_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
